version: 0.2

phases:
  build:
    commands:
      - aws deploy push --application-name finalworkdeploy --s3-location s3://finalworkbucket/artifact.zip --source src
artifacts:
  files:
    - '**/*'
  base-directory: src